#pragma once
#include "Common.h"

int main();
void ExecKnock32(void);
void ExecKnock31(void);
void ExecKnock30(void);
void ExecKnock29(void);
void ExecKnock28(void);
void ExecKnock27(void);
void ExecKnock26(void);
void ExecKnock25(void);
void ExecKnock24(void);
void ExecKnock23(void);
void ExecKnock22(void);
void ExecKnock21(void);
void ExecKnock20(void);
void ExecKnock19(void);
void ExecKnock18(void);
void ExecKnock17(void);
void ExecKnock16(void);
void ExecKnock15(void);
void ExecKnock14(void);
void ExecKnock13(void);
void ExecKnock12(void);
void ExecKnock11(void);
void ExecKnock10(void);
void ExecKnock09(void);
void ExecKnock08(void);
void ExecKnock07(void);
void ExecKnock06(void);
void ExecKnock05(void);
void ExecKnock04(void);
void ExecKnock03(void);
void ExecKnock02(void);
void ExecKnock01(void);
void ExecKnock00(void);
